---
- include_tasks: checkinternet.yml



#- name: install elrepo
#  yum:
#    name: http://www.elrepo.org/elrepo-release-7.0-3.el7.elrepo.noarch.rpm
#    state: present


- name: Set a hostname
  hostname: name={{ hostname }}
  tags: set hostname

- name: update /etc/hosts file
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'templates/hosts.j2') }}"
    state: present
  tags: modify hosts

- name: stop & disable firewalld
  systemd:
    name: firewalld.service
    state: stopped
    enabled: no
  tags: stop firewalld
   
- name: clear iptables
  iptables:
    flush: yes

- name: swap off
  shell: swapoff -a && sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab 
  tags: swap off
 
- name: disable selinux
  selinux:
    state: disabled
  tags: disable selinux
  
#- name: modify sysctl
#  get_url:
#    url: "{{ httpurl }}/{{ ansible_role_name }}/kubernetes.conf"
#    dest: /etc/sysctl.d/kubernetes.conf
#
- name: modify sysctl
  copy:
    src: files/kubernetes.conf
    dest: /etc/sysctl.d/kubernetes.conf
#  #notify:
#  #  - name: reboot machine
#  tags: modify sysctl

- name: set timezone
  timezone:
    name: Asia/Shanghai



- name: install chrony
  yum:
    name: chrony
    state: present

- name: copy chrony conf
  template:
    src: ../templates/chrony.conf.j2
    dest: /etc/chrony.conf
  notify:
    - restart chronyd

